# Taps
tap 'homebrew/bundle'
tap 'aws/tap'
tap 'saulpw/vd'

cask "alt-tab" # Windows style CMD+Tab previews
cask "appcleaner"
cask "coconutbattery"
cask "discord"
cask "iina"
cask "insomnia"
# cask "iterm2"
cask "maccy"
cask "usr-sse2-rdm"
cask "rectangle" # Window Manager
cask "secretive" # Use TouchID to guard SSH Keys
cask "spotify"
cask "ticktick"
cask "visual-studio-code"

# Quicklook Extensions
cask 'qlmarkdown'
cask 'quicklook-json'

# Basic terminal stuff
brew "coreutils" # The MacOS built in ones are shit
brew "starship"
brew "zsh" # Zsh comes installed but is slightly out of date
brew "zsh-autosuggestions"

# Terminal window management
brew "tmux"

# Tooling
brew "awscli"
brew "bat" # Cat with wings!
brew "cmake"
brew "ffmpeg"
brew "fzf" # Fuzzy finder for terminal
brew "git"
brew "git-delta" # Superior diffing tool, used for Git
brew "git-interactive-rebase-tool"
brew "httpie"
brew "htop"
brew "imagemagick"
brew "jq"
brew "libomp"
brew "lsd" # Better LS alternative
brew "neovim"
brew "rsync"
brew "the_silver_searcher" # Ag for Zsh
brew "tree"
brew "uv"
brew "visidata"
brew "wget"
