set -g default-terminal "$TERM"

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1

# don't rename windows automatically
set -g allow-rename off
set -g automatic-rename off

# Use vim keybindings in copy mode
setw -g mode-keys vi

# use emacs for status bar
set -g status-keys emacs

# Reload the environment when creating or attaching to a session
set -g update-environment 'DISPLAY SSH_ASKPASS SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY TERM'

# do not wait after pressing escape. (speed up vim escape)
set -g escape-time 0

set -g history-limit 10000

# Keep a 'gapless' window history
set -g renumber-windows on

# Mouse support
set -g mouse on

# keybinds
source-file ~/.config/tmux/bindings.conf

# setup platform specific options
# run-shell ~/.config/tmux/scripts/platform.sh

set -g @plugin '2kabhishek/tmux2k'
set -g @plugin 'jaclu/tmux-menus'
# set -g @plugin 'toddyamakawa/tmux-prefixless'
set -g @plugin 'ofirgall/tmux-window-name'
set -g @plugin 'alexwforsythe/tmux-which-key'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# apply stylistic theming configurations
source-file ~/.config/tmux/nightfox.conf

# Start with an empty session so we may immediately attach
new-session -A -s main

